#!/bin/bash


GEMDIR=$(ruby -e 'puts Gem.default_dir')


abinfo "设置 Bundler 配置..."
sed -e '/BUNDLED WITH/,+1d' -i Gemfile.lock


bundle config build.nokogiri --use-system-libraries
bundle config set --local deployment 'true'
bundle config set --local no-cache 'true'
bundle config set path "$PKGDIR$GEMDIR"


sed 's|git ls-files|find -type f|' -i metasploit-framework.gemspec

abinfo "正在使用 Bundler 安装依赖..."
bundle install -j"$(nproc)" --no-cache

abinfo "调整文件权限..."

abinfo "调整文件权限..."
find "$PKGDIR$GEMDIR" -exec chmod o+r '{}' \;


abinfo "创建可执行文件脚本..."
for script in msfconsole msfvenom msfrpc msfrpcd msfd; do

  mkdir -p "$PKGDIR/usr/bin"


  script_path="$PKGDIR/usr/bin/$script"
  echo -e "#!/bin/bash\nBUNDLE_GEMFILE=/opt/metasploit/Gemfile exec bundle exec ruby /opt/metasploit/$script \"\$@\"" > "$script_path"
  chmod 755 "$script_path"
done


abinfo "设置工具脚本..."

tools_dir="$PKGDIR/opt/metasploit/"


mkdir -p "$tools_dir"


rsync -a --exclude="$PKGDIR" "$SRCDIR/" "$tools_dir"

chmod -R 775 $PKGDIR/*